language: objective-c
osx_image: xcode7.1
# xcode_project: ./SwiftJson/SwiftJson.xcodeproj
# xcode_scheme: SwiftJson
script:
  - xcodebuild -project ./SwiftJson/SwiftJson.xcodeproj -target SwiftJson -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild test -project ./SwiftJson/SwiftJson.xcodeproj -scheme SwiftJson -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
